[2023-05-24T12:12:17.440+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-task.create_table scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T12:12:17.447+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-task.create_table scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T12:12:17.448+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T12:12:17.449+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-24T12:12:17.449+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T12:12:17.457+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-23 00:00:00+00:00
[2023-05-24T12:12:17.461+0000] {standard_task_runner.py:55} INFO - Started process 484 to run task
[2023-05-24T12:12:17.465+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'docker-task', 'create_table', 'scheduled__2023-05-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/docker-task.py', '--cfg-path', '/tmp/tmp_3ly2y59']
[2023-05-24T12:12:17.466+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask create_table
[2023-05-24T12:12:17.515+0000] {task_command.py:388} INFO - Running <TaskInstance: docker-task.create_table scheduled__2023-05-23T00:00:00+00:00 [running]> on host fe8636e26e35
[2023-05-24T12:12:17.560+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker-task
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-23T00:00:00+00:00
[2023-05-24T12:12:17.561+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users(
                first_name varchar(255) not null
            );
        
[2023-05-24T12:12:17.576+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-05-24T12:12:17.579+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=docker-task, task_id=create_table, execution_date=20230523T000000, start_date=20230524T121217, end_date=20230524T121217
[2023-05-24T12:12:17.586+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task create_table (The conn_id `postgres` isn't defined; 484)
[2023-05-24T12:12:17.598+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-24T12:12:17.611+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
